name: Parallel Script tests
on: push
jobs:
  addtocart-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
            command: npm run test:addtocart

      - name: Cypress Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
             name: Mochawesome HTML Reports - AddToCart Flow
             path: cypress/reports/html # or path/to/artifact

  registration-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
            command: npm run test:register

      - name: Cypress Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
             name: Mochawesome HTML Reports - Register Flow
             path: cypress/reports/html # or path/to/artifact